# build environment
FROM node:14.16.0-alpine as build
WORKDIR /app
COPY build build

#! insert final stage from "./Dockerfile"

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]